version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

python:
   install:
      - method: pip
        path: .

conda:
  environment: docs/conda_env_docs.yml